{{- if .Values.ingress.enabled }}
{{- $isDQA := .Values.is_dqa -}}
{{- $envName := .Values.env_name }}
{{- $serviceName := .Values.service.name }}
{{- $servicePort := .Values.service.internalPort }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.ingress_class }}"
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
      {{- if $isDQA }}
      - host: {{ $envName }}-{{ $host }}
      {{- else }}
      - host: {{ $host }}
      {{- end }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
{{- end }}
