# Default values for acyl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
maxSurge: 4
namespace: default
create_svc: true
create_cluster_role_binding: false
is_dqa: false
run_migrations: false
enable_cronjob: false
image:
  repository: quay.io/dollarshaveclub/acyl
  tag: master
  pullPolicy: Always
  pullSecret: pull-secret
app:
  env_limit: '80'
  disable_tls: true  # required for argo ingress
  secrets_backend: "vault"
  secrets_mapping: "{{ .ID }}"
  secrets_from_env: false
  debug_endpoints: true
  consul_server_host: 1.2.3.4
  datadog_service_name: acyl
  dogstatsd_addr: 1.2.3.4:8125
  datadog_tracing_agent_addr: 1.2.3.4:8126
  metrics_tags: ''
  furan_addr: "furan"
  k8s_group_bindings: ""
  k8s_secret_injections: "image-pull-secret=k8s/image_pull_secret"
  k8s_client_disable_http2: true # work around bug in using HTTP2 for k8s client calls
  operation_timeout_override: ''
  ui:
    base_url: 'http://localhost:4000'
    enforce_oauth: false
    branding:
      logo_url: ''
      logo_width: ''
      logo_height: ''
      logo_link: ''
      logo_alt: ''
      logo_style: ''
      favicon_url: ''
      title: ''
      title_style: ''
  failure_reports:
    s3:
      region: ''
      bucket: ''
      keyprefix: 'acyl/'
  cleanup:
    legacy_reaper_interval_secs: 300
    schedule: "@hourly"
    k8s_max_age: 336h # 14 days
    destroyed_envs_max_age: 720h # 30 days
    event_logs_max_age: 720h
vault:
  addr: https://vault:8200
  use_k8s_auth: true
  role: acyl
  auth_path: "kubernetes"
  agent_injector:
    enabled: false
    init_first: false
    log_level: info
  secrets_prefix: "secret/services/acyl/qa/"
  secrets:
  - name: awsAccessKeyID
    path: aws/access_key_id
  - name: awsSecretAccessKey
    path: aws/secret_access_key
  - name: githubHookSecretid         
    path: github/hook_secret
  - name: githubTokenid
    path: github/token
  - name: githubAppID                
    path: github/app/id
  - name: githubAppPK                
    path: github/app/private_key
  - name: githubAppHookSecret        
    path: github/app/hook_secret
  - name: githubOAuthInstID          
    path: github/app/oauth/installation_id
  - name: githubOAuthClientID        
    path: github/app/oauth/client/id
  - name: githubOAuthClientSecret    
    path: github/app/oauth/client/secret
  - name: githubOAuthCookieEncKey    
    path: github/app/oauth/cookie/encryption_key
  - name: githubOAuthCookieAuthKey   
    path: github/app/oauth/cookie/authentication_key
  - name: githubOAuthUserTokenEncKey 
    path: github/app/oauth/user_token/encryption_key
  - name: apiKeysid                  
    path: api_keys
  - name: slackTokenid               
    path: slack/token
  - name: tlsCertid                  
    path: tls/cert
  - name: tlsKeyid                   
    path: tls/key
  - name: dbURIid                    
    path: db/uri

cronautoscaling:
  enabled: false
  jobs: []
serviceaccount: serviceaccount
service:
  name: acyl
  type: ClusterIP
  internalPort: 4000
ingress:
  argo: true
  argo_host: foo.bar.com
  traefik:
    entry_point: web
    enabled: false
    ingress_class: 'traefik'
    host: foo.bar.com
rbac:
  cluster_role: cluster-admin
  cluster_role_binding:
    name: acyl
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 256Mi

